apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: kubernetes
spec:
  forProvider:
    name: kubernetes
    clientId: kubernetes
    accessType: CONFIDENTIAL
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: true
    authorization:
      - policyEnforcementMode: ENFORCING
    validRedirectUris:
      - http://localhost:18000
      - http://localhost:8000
    realmId: myrealm
  providerConfigRef:
    name: keycloak-provider-config