apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: ProtocolMapper
metadata:
  name: kubernetes-name
spec:
  forProvider:
    clientIdRef: 
      name: kubernetes
    config:
      access.token.claim: "true"
      claim.name: name
      id.token.claim: "true"
      user.attribute: name
    name: name
    protocol: openid-connect
    protocolMapper: oidc-usermodel-attribute-mapper
    realmId: myrealm
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: ProtocolMapper
metadata:
  name: kubernetes-roles
spec:
  forProvider:
    clientIdRef: 
      name: kubernetes
    config:
      usermodel.clientRoleMapping.clientId: kubernetes
      access.token.claim: "true"
      claim.name: roles
      id.token.claim: "true"
      multivalued: "true"
    name: roles
    protocol: openid-connect
    protocolMapper: oidc-usermodel-client-role-mapper
    realmId: myrealm
  providerConfigRef:
    name: keycloak-provider-config